author_1 = Author.create(name: Faker::Book.unique.author)
author_2 = Author.create(name: Faker::Book.unique.author)
author_3 = Author.create(name: Faker::Book.unique.author)
author_4 = Author.create(name: Faker::Book.unique.author)
author_5 = Author.create(name: Faker::Book.unique.author)
author_6 = Author.create(name: Faker::Book.unique.author)


book_1 = Book.create(authors: [author_1], title: Faker::Book.unique.title, pages: Faker::Number.number(3), published_year: Faker::Stripe.year, img: 'https://www.unboundworlds.com/wp-content/uploads/2018/06/chris-lawton-236416-unsplash.jpg')
book_2 = Book.create(authors: [author_1, author_2], title: Faker::Book.unique.title, pages: Faker::Number.number(3), published_year: Faker::Stripe.year, img: 'https://www.unboundworlds.com/wp-content/uploads/2018/06/chris-lawton-236416-unsplash.jpg')
book_3 = Book.create(authors: [author_2], title: Faker::Book.unique.title, pages: Faker::Number.number(3), published_year: Faker::Stripe.year, img: 'https://www.unboundworlds.com/wp-content/uploads/2018/06/chris-lawton-236416-unsplash.jpg')
book_4 = Book.create(authors: [author_3], title: Faker::Book.unique.title, pages: Faker::Number.number(3), published_year: Faker::Stripe.year, img: 'https://www.unboundworlds.com/wp-content/uploads/2018/06/chris-lawton-236416-unsplash.jpg')
book_5 = Book.create(authors: [author_3, author_4], title: Faker::Book.unique.title, pages: Faker::Number.number(3), published_year: Faker::Stripe.year, img: 'https://www.unboundworlds.com/wp-content/uploads/2018/06/chris-lawton-236416-unsplash.jpg')
book_6 = Book.create(authors: [author_4], title: Faker::Book.unique.title, pages: Faker::Number.number(3), published_year: Faker::Stripe.year, img: 'https://www.unboundworlds.com/wp-content/uploads/2018/06/chris-lawton-236416-unsplash.jpg')
book_7 = Book.create(authors: [author_5], title: Faker::Book.unique.title, pages: Faker::Number.number(3), published_year: Faker::Stripe.year, img: 'https://www.unboundworlds.com/wp-content/uploads/2018/06/chris-lawton-236416-unsplash.jpg')
book_8 = Book.create(authors: [author_4, author_5], title: Faker::Book.unique.title, pages: Faker::Number.number(3), published_year: Faker::Stripe.year, img: 'https://www.unboundworlds.com/wp-content/uploads/2018/06/chris-lawton-236416-unsplash.jpg')
book_9 = Book.create(authors: [author_6], title: Faker::Book.unique.title, pages: Faker::Number.number(3), published_year: Faker::Stripe.year, img: 'https://www.unboundworlds.com/wp-content/uploads/2018/06/chris-lawton-236416-unsplash.jpg')
book_10 = Book.create(authors: [author_3, author_6], title: Faker::Book.unique.title, pages: Faker::Number.number(3), published_year: Faker::Stripe.year, img: 'https://www.unboundworlds.com/wp-content/uploads/2018/06/chris-lawton-236416-unsplash.jpg')
book_11 = Book.create(authors: [author_1, author_5], title: Faker::Book.unique.title, pages: Faker::Number.number(3), published_year: Faker::Stripe.year, img: 'https://www.unboundworlds.com/wp-content/uploads/2018/06/chris-lawton-236416-unsplash.jpg')
book_12 = Book.create(authors: [author_5], title: Faker::Book.unique.title, pages: Faker::Number.number(3), published_year: Faker::Stripe.year, img: 'https://www.unboundworlds.com/wp-content/uploads/2018/06/chris-lawton-236416-unsplash.jpg')

user_1 = User.create(name: Faker::Internet.username(9..15).downcase.titlecase)
user_2 = User.create(name: Faker::Internet.username(9..15).downcase.titlecase)
user_3 = User.create(name: Faker::Internet.username(9..15).downcase.titlecase)
user_4 = User.create(name: Faker::Internet.username(9..15).downcase.titlecase)
user_5 = User.create(name: Faker::Internet.username(9..15).downcase.titlecase)

Review.create(user: user_1, book: book_1, title: Faker::Food.dish, description: Faker::Hacker.say_something_smart, rating: (Faker::Number.between(1,10) / 2.to_f), created_at: 50.days.ago)
Review.create(user: user_2, book: book_2, title: Faker::Food.dish, description: Faker::Hacker.say_something_smart, rating: (Faker::Number.between(1,10) / 2.to_f), created_at: 45.days.ago)
Review.create(user: user_3, book: book_2, title: Faker::Food.dish, description: Faker::Hacker.say_something_smart, rating: (Faker::Number.between(1,10) / 2.to_f), created_at: 40.days.ago)
Review.create(user: user_4, book: book_3, title: Faker::Food.dish, description: Faker::Hacker.say_something_smart, rating: (Faker::Number.between(1,10) / 2.to_f), created_at: 35.days.ago)
Review.create(user: user_5, book: book_3, title: Faker::Food.dish, description: Faker::Hacker.say_something_smart, rating: (Faker::Number.between(1,10) / 2.to_f), created_at: 30.days.ago)
Review.create(user: user_5, book: book_3, title: Faker::Food.dish, description: Faker::Hacker.say_something_smart, rating: (Faker::Number.between(1,10) / 2.to_f), created_at: 25.days.ago)
Review.create(user: user_2, book: book_4, title: Faker::Food.dish, description: Faker::Hacker.say_something_smart, rating: (Faker::Number.between(1,10) / 2.to_f), created_at: 20.days.ago)
Review.create(user: user_3, book: book_4, title: Faker::Food.dish, description: Faker::Hacker.say_something_smart, rating: (Faker::Number.between(1,10) / 2.to_f), created_at: 15.days.ago)
Review.create(user: user_4, book: book_4, title: Faker::Food.dish, description: Faker::Hacker.say_something_smart, rating: (Faker::Number.between(1,10) / 2.to_f), created_at: 14.days.ago)
Review.create(user: user_5, book: book_4, title: Faker::Food.dish, description: Faker::Hacker.say_something_smart, rating: (Faker::Number.between(1,10) / 2.to_f), created_at: 13.days.ago)
Review.create(user: user_5, book: book_5, title: Faker::Food.dish, description: Faker::Hacker.say_something_smart, rating: (Faker::Number.between(1,10) / 2.to_f), created_at: 12.days.ago)
Review.create(user: user_4, book: book_5, title: Faker::Food.dish, description: Faker::Hacker.say_something_smart, rating: (Faker::Number.between(1,10) / 2.to_f), created_at: 11.days.ago)
Review.create(user: user_3, book: book_1, title: Faker::Food.dish, description: Faker::Hacker.say_something_smart, rating: (Faker::Number.between(1,10) / 2.to_f), created_at: 10.days.ago)
Review.create(user: user_4, book: book_2, title: Faker::Food.dish, description: Faker::Hacker.say_something_smart, rating: (Faker::Number.between(1,10) / 2.to_f), created_at: 9.days.ago)
Review.create(user: user_5, book: book_3, title: Faker::Food.dish, description: Faker::Hacker.say_something_smart, rating: (Faker::Number.between(1,10) / 2.to_f), created_at: 8.days.ago)
Review.create(user: user_2, book: book_4, title: Faker::Food.dish, description: Faker::Hacker.say_something_smart, rating: (Faker::Number.between(1,10) / 2.to_f), created_at: 7.days.ago)
Review.create(user: user_2, book: book_5, title: Faker::Food.dish, description: Faker::Hacker.say_something_smart, rating: (Faker::Number.between(1,10) / 2.to_f), created_at: 6.days.ago)
Review.create(user: user_5, book: book_6, title: Faker::Food.dish, description: Faker::Hacker.say_something_smart, rating: (Faker::Number.between(1,10) / 2.to_f), created_at: 5.days.ago)
Review.create(user: user_5, book: book_7, title: Faker::Food.dish, description: Faker::Hacker.say_something_smart, rating: (Faker::Number.between(1,10) / 2.to_f), created_at: 4.days.ago)
Review.create(user: user_5, book: book_8, title: Faker::Food.dish, description: Faker::Hacker.say_something_smart, rating: (Faker::Number.between(1,10) / 2.to_f), created_at: 3.days.ago)
Review.create(user: user_5, book: book_9, title: Faker::Food.dish, description: Faker::Hacker.say_something_smart, rating: (Faker::Number.between(1,10) / 2.to_f), created_at: 2.days.ago)
Review.create(user: user_5, book: book_10, title: Faker::Food.dish, description: Faker::Hacker.say_something_smart, rating: (Faker::Number.between(1,10) / 2.to_f), created_at: 1.days.ago)
Review.create(user: user_5, book: book_11, title: Faker::Food.dish, description: Faker::Hacker.say_something_smart, rating: (Faker::Number.between(1,10) / 2.to_f), created_at: 33.days.ago)
Review.create(user: user_5, book: book_12, title: Faker::Food.dish, description: Faker::Hacker.say_something_smart, rating: (Faker::Number.between(1,10) / 2.to_f), created_at: 31.days.ago)
